name: "Mikael Viima"
url: "https://www.mikaelviima.com"
nav_primary:
  - label: "Poetry"
    url: "/poetry/"
  - label: "Books"
    url: "/books/"
  - label: "About"
    url: "/about/"
  - label: "Contact"
    url: "/contact/"
nav_footer:
  - label: "Press"
    url: "/press/"
